"""add_compliance_models

Revision ID: 2286ae4ccb19
Revises: e54e366fb904
Create Date: 2026-07-31 09:44:06.568617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2286ae4ccb19'
down_revision: Union[str, Sequence[str], None] = 'e54e366fb904'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('do_not_contact',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_do_not_contact_created_at'), 'do_not_contact', ['created_at'], unique=False)
    op.create_index(op.f('ix_do_not_contact_tenant_id'), 'do_not_contact', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_do_not_contact_value'), 'do_not_contact', ['value'], unique=False)
    op.create_table('compliance_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('prospect_id', sa.String(length=36), nullable=True),
    sa.Column('policy_type', sa.Enum('DO_NOT_CONTACT', 'UNSUBSCRIBE', 'BOUNCE', 'INVALID_EMAIL', 'DAILY_LIMIT', 'RATE_LIMIT', 'BUSINESS_HOURS', 'COOLDOWN', 'DUPLICATE_PREVENTION', 'MEETING_BOOKED', 'DISQUALIFIED', 'CONSENT_MISSING', name='compliancepolicytype'), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'WARNING', 'TEMPORARY_BLOCK', 'PERMANENT_BLOCK', name='policyseverity'), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('metadata_', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['prospect_id'], ['prospects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_logs_created_at'), 'compliance_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_compliance_logs_policy_type'), 'compliance_logs', ['policy_type'], unique=False)
    op.create_index(op.f('ix_compliance_logs_prospect_id'), 'compliance_logs', ['prospect_id'], unique=False)
    op.create_index(op.f('ix_compliance_logs_tenant_id'), 'compliance_logs', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_compliance_logs_tenant_id'), table_name='compliance_logs')
    op.drop_index(op.f('ix_compliance_logs_prospect_id'), table_name='compliance_logs')
    op.drop_index(op.f('ix_compliance_logs_policy_type'), table_name='compliance_logs')
    op.drop_index(op.f('ix_compliance_logs_created_at'), table_name='compliance_logs')
    op.drop_table('compliance_logs')
    op.drop_index(op.f('ix_do_not_contact_value'), table_name='do_not_contact')
    op.drop_index(op.f('ix_do_not_contact_tenant_id'), table_name='do_not_contact')
    op.drop_index(op.f('ix_do_not_contact_created_at'), table_name='do_not_contact')
    op.drop_table('do_not_contact')
    # ### end Alembic commands ###
