"""add_conversation_memory

Revision ID: 4b083897ce1b
Revises: 2fe6324f4da1
Create Date: 2026-07-31 09:08:24.266627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4b083897ce1b'
down_revision: Union[str, Sequence[str], None] = '2fe6324f4da1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_memories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('prospect_id', sa.String(length=36), nullable=False),
    sa.Column('memory_type', sa.Enum('LINKEDIN_MESSAGE', 'EMAIL_MESSAGE', 'CALL_SUMMARY', 'AI_NOTE', 'OBJECTION', 'PREFERENCE', 'MEETING_OUTCOME', name='memorytype'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('importance_score', sa.Integer(), nullable=False),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata_', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['prospect_id'], ['prospects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_memories_created_at'), 'conversation_memories', ['created_at'], unique=False)
    op.create_index(op.f('ix_conversation_memories_prospect_id'), 'conversation_memories', ['prospect_id'], unique=False)
    op.create_index(op.f('ix_conversation_memories_tenant_id'), 'conversation_memories', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversation_memories_tenant_id'), table_name='conversation_memories')
    op.drop_index(op.f('ix_conversation_memories_prospect_id'), table_name='conversation_memories')
    op.drop_index(op.f('ix_conversation_memories_created_at'), table_name='conversation_memories')
    op.drop_table('conversation_memories')
    # ### end Alembic commands ###
