"""add_correlation_ids

Revision ID: 7aef95d2f6de
Revises: 7fea3d691ca5
Create Date: 2026-07-31 10:44:04.174727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7aef95d2f6de'
down_revision: Union[str, Sequence[str], None] = '7fea3d691ca5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity_timelines', sa.Column('correlation_id', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_activity_timelines_correlation_id'), 'activity_timelines', ['correlation_id'], unique=False)
    op.add_column('compliance_logs', sa.Column('action_taken', sa.String(length=50), nullable=False))
    op.add_column('compliance_logs', sa.Column('correlation_id', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_compliance_logs_correlation_id'), 'compliance_logs', ['correlation_id'], unique=False)
    op.add_column('decision_logs', sa.Column('correlation_id', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_decision_logs_correlation_id'), 'decision_logs', ['correlation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_decision_logs_correlation_id'), table_name='decision_logs')
    op.drop_column('decision_logs', 'correlation_id')
    op.drop_index(op.f('ix_compliance_logs_correlation_id'), table_name='compliance_logs')
    op.drop_column('compliance_logs', 'correlation_id')
    op.drop_column('compliance_logs', 'action_taken')
    op.drop_index(op.f('ix_activity_timelines_correlation_id'), table_name='activity_timelines')
    op.drop_column('activity_timelines', 'correlation_id')
    # ### end Alembic commands ###
