"""add_voice_ai_tables

Revision ID: 7fea3d691ca5
Revises: 2286ae4ccb19
Create Date: 2026-07-31 09:55:41.896780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7fea3d691ca5'
down_revision: Union[str, Sequence[str], None] = '2286ae4ccb19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('call_transcripts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('prospect_id', sa.String(length=36), nullable=False),
    sa.Column('call_sid', sa.String(length=100), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('total_turns', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('incremental_summary', sa.Text(), nullable=True),
    sa.Column('metadata_', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['prospect_id'], ['prospects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_call_transcripts_call_sid'), 'call_transcripts', ['call_sid'], unique=False)
    op.create_index(op.f('ix_call_transcripts_created_at'), 'call_transcripts', ['created_at'], unique=False)
    op.create_index(op.f('ix_call_transcripts_prospect_id'), 'call_transcripts', ['prospect_id'], unique=False)
    op.create_index(op.f('ix_call_transcripts_tenant_id'), 'call_transcripts', ['tenant_id'], unique=False)
    op.create_table('call_transcript_lines',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('transcript_id', sa.String(length=36), nullable=False),
    sa.Column('turn_index', sa.Integer(), nullable=False),
    sa.Column('speaker', sa.String(length=20), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('intent', sa.String(length=50), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['transcript_id'], ['call_transcripts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_call_transcript_lines_tenant_id'), 'call_transcript_lines', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_call_transcript_lines_transcript_id'), 'call_transcript_lines', ['transcript_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_call_transcript_lines_transcript_id'), table_name='call_transcript_lines')
    op.drop_index(op.f('ix_call_transcript_lines_tenant_id'), table_name='call_transcript_lines')
    op.drop_table('call_transcript_lines')
    op.drop_index(op.f('ix_call_transcripts_tenant_id'), table_name='call_transcripts')
    op.drop_index(op.f('ix_call_transcripts_prospect_id'), table_name='call_transcripts')
    op.drop_index(op.f('ix_call_transcripts_created_at'), table_name='call_transcripts')
    op.drop_index(op.f('ix_call_transcripts_call_sid'), table_name='call_transcripts')
    op.drop_table('call_transcripts')
    # ### end Alembic commands ###
