"""baseline schema

Revision ID: 83a7af0da17a
Revises: 
Create Date: 2026-07-30 12:05:30.730829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '83a7af0da17a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaigns_tenant_id'), 'campaigns', ['tenant_id'], unique=False)
    op.create_table('workspace_settings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('follow_up_delay_hours', sa.Integer(), nullable=False),
    sa.Column('call_delay_hours', sa.Integer(), nullable=False),
    sa.Column('max_follow_ups', sa.Integer(), nullable=False),
    sa.Column('working_hours_start', sa.String(length=5), nullable=False),
    sa.Column('working_hours_end', sa.String(length=5), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('exclude_weekends', sa.Boolean(), nullable=False),
    sa.Column('dev_mode', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspace_settings_tenant_id'), 'workspace_settings', ['tenant_id'], unique=False)
    op.create_table('prospects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('campaign_id', sa.String(length=36), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('linkedin_url', sa.Text(), nullable=False),
    sa.Column('phone_number', sa.String(length=30), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('company_domain', sa.String(length=255), nullable=True),
    sa.Column('provider_id', sa.String(length=100), nullable=True),
    sa.Column('current_state', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('IDLE', 'LI_REQ_SENT', 'LI_ACCEPTED_NO_MSG', 'LI_MSG_SENT', 'LINKEDIN_NO_RESPONSE', 'EMAIL_SENT', 'EMAIL_OPENED', 'EMAIL_CLICKED', 'EMAIL_FAILED', 'CALL_QUEUED', 'CALL_IN_PROGRESS', 'CALL_NO_ANSWER_1', 'CALL_NO_ANSWER_2', 'CALL_FAILED', 'CALL_RETRY', 'MEETING_BOOKED', 'PAUSED_NUDGED', 'COMPLETED_DECLINED', 'UNRESPONSIVE_DEAD', 'LOST', 'ERROR_NEEDS_HUMAN', 'ENGAGED_ON_WEBSITE', name='prospectstatus'), nullable=False),
    sa.Column('call_attempts', sa.Integer(), nullable=False),
    sa.Column('last_call_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_action_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('last_status_change_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_prospects_tenant_state', 'prospects', ['tenant_id', 'current_state'], unique=False)
    op.create_index(op.f('ix_prospects_current_state'), 'prospects', ['current_state'], unique=False)
    op.create_index(op.f('ix_prospects_email'), 'prospects', ['email'], unique=False)
    op.create_index(op.f('ix_prospects_provider_id'), 'prospects', ['provider_id'], unique=False)
    op.create_index(op.f('ix_prospects_tenant_id'), 'prospects', ['tenant_id'], unique=False)
    op.create_table('sequence_rules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('campaign_id', sa.String(length=36), nullable=True),
    sa.Column('max_linkedin_msgs', sa.Integer(), nullable=False),
    sa.Column('linkedin_interval_minutes', sa.Integer(), nullable=False),
    sa.Column('max_emails', sa.Integer(), nullable=False),
    sa.Column('email_interval_minutes', sa.Integer(), nullable=False),
    sa.Column('max_calls', sa.Integer(), nullable=False),
    sa.Column('call_interval_minutes', sa.Integer(), nullable=False),
    sa.Column('response_handling_action', sa.String(length=50), nullable=False),
    sa.Column('ai_guided_calls', sa.Boolean(), nullable=False),
    sa.Column('call_mode', sa.String(length=20), nullable=False),
    sa.Column('assigned_lead_owner_id', sa.String(length=64), nullable=True),
    sa.Column('auto_handover_to_admin', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sequence_rules_tenant_id'), 'sequence_rules', ['tenant_id'], unique=False)
    op.create_table('activity_timelines',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('prospect_id', sa.String(length=36), nullable=False),
    sa.Column('channel', sa.String(length=30), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['prospect_id'], ['prospects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_timelines_tenant_id'), 'activity_timelines', ['tenant_id'], unique=False)
    op.create_table('follow_ups',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('prospect_id', sa.String(length=36), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['prospect_id'], ['prospects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_followups_status_scheduled', 'follow_ups', ['status', 'scheduled_for'], unique=False)
    op.create_index(op.f('ix_follow_ups_scheduled_for'), 'follow_ups', ['scheduled_for'], unique=False)
    op.create_index(op.f('ix_follow_ups_status'), 'follow_ups', ['status'], unique=False)
    op.create_index(op.f('ix_follow_ups_tenant_id'), 'follow_ups', ['tenant_id'], unique=False)
    op.create_table('sequence_steps',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('sequence_rule_id', sa.String(length=36), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('delay_minutes', sa.Integer(), nullable=False),
    sa.Column('template_prompt', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['sequence_rule_id'], ['sequence_rules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workflow_states',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('prospect_id', sa.String(length=36), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['prospect_id'], ['prospects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prospect_id')
    )
    op.create_index(op.f('ix_workflow_states_tenant_id'), 'workflow_states', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflow_states_tenant_id'), table_name='workflow_states')
    op.drop_table('workflow_states')
    op.drop_table('sequence_steps')
    op.drop_index(op.f('ix_follow_ups_tenant_id'), table_name='follow_ups')
    op.drop_index(op.f('ix_follow_ups_status'), table_name='follow_ups')
    op.drop_index(op.f('ix_follow_ups_scheduled_for'), table_name='follow_ups')
    op.drop_index('idx_followups_status_scheduled', table_name='follow_ups')
    op.drop_table('follow_ups')
    op.drop_index(op.f('ix_activity_timelines_tenant_id'), table_name='activity_timelines')
    op.drop_table('activity_timelines')
    op.drop_index(op.f('ix_sequence_rules_tenant_id'), table_name='sequence_rules')
    op.drop_table('sequence_rules')
    op.drop_index(op.f('ix_prospects_tenant_id'), table_name='prospects')
    op.drop_index(op.f('ix_prospects_provider_id'), table_name='prospects')
    op.drop_index(op.f('ix_prospects_email'), table_name='prospects')
    op.drop_index(op.f('ix_prospects_current_state'), table_name='prospects')
    op.drop_index('idx_prospects_tenant_state', table_name='prospects')
    op.drop_table('prospects')
    # autogenerate's drop_table doesn't drop the native enum type it created;
    # do so explicitly or a later upgrade fails with "type already exists".
    sa.Enum(name='prospectstatus').drop(op.get_bind(), checkfirst=True)
    op.drop_index(op.f('ix_workspace_settings_tenant_id'), table_name='workspace_settings')
    op.drop_table('workspace_settings')
    op.drop_index(op.f('ix_campaigns_tenant_id'), table_name='campaigns')
    op.drop_table('campaigns')
    # ### end Alembic commands ###
