"""add google calendar sync

Revision ID: 9d1e2763b279
Revises: a6982c16e0bb
Create Date: 2026-07-30 13:48:26.373259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d1e2763b279'
down_revision: Union[str, Sequence[str], None] = 'a6982c16e0bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar_sync_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('prospect_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.Enum('SUCCESS', 'FAILED', 'PENDING', name='calendarsyncstatus'), nullable=False),
    sa.Column('google_event_id', sa.String(length=128), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['prospect_id'], ['prospects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calendar_sync_logs_created_at'), 'calendar_sync_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_calendar_sync_logs_prospect_id'), 'calendar_sync_logs', ['prospect_id'], unique=False)
    op.create_index(op.f('ix_calendar_sync_logs_tenant_id'), 'calendar_sync_logs', ['tenant_id'], unique=False)
    op.add_column('prospects', sa.Column('google_calendar_event_id', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column('prospects', 'google_calendar_event_id')
    op.drop_index(op.f('ix_calendar_sync_logs_tenant_id'), table_name='calendar_sync_logs')
    op.drop_index(op.f('ix_calendar_sync_logs_prospect_id'), table_name='calendar_sync_logs')
    op.drop_index(op.f('ix_calendar_sync_logs_created_at'), table_name='calendar_sync_logs')
    op.drop_table('calendar_sync_logs')
    # autogenerate's drop_table doesn't drop the native enum type it created;
    # do so explicitly or a later upgrade fails with "type already exists"
    # (same issue found in the Module 1 CRM migration).
    sa.Enum(name='calendarsyncstatus').drop(op.get_bind(), checkfirst=True)
