"""add_buying_signals

Revision ID: e54e366fb904
Revises: 4b083897ce1b
Create Date: 2026-07-31 09:28:58.144778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e54e366fb904'
down_revision: Union[str, Sequence[str], None] = '4b083897ce1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buying_signals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('prospect_id', sa.String(length=36), nullable=False),
    sa.Column('signal_type', sa.Enum('WEBSITE_VISIT', 'LINKEDIN_ACTIVITY', 'JOB_CHANGE', 'PROMOTION', 'COMPANY_HIRING', 'FUNDING_EVENT', 'NEWS_EVENT', 'TECH_STACK_CHANGE', 'EMAIL_OPEN', 'EMAIL_CLICK', 'CALLBACK_REQUEST', 'HIGH_INTENT_REPLY', 'NEGATIVE_REPLY', 'MEETING_REQUEST', 'MANUAL_SIGNAL', 'CUSTOM_SIGNAL', name='signaltype'), nullable=False),
    sa.Column('signal_source', sa.String(length=100), nullable=False),
    sa.Column('signal_strength', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'VERY_HIGH', name='signalstrength'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('metadata_', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['prospect_id'], ['prospects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_buying_signals_created_at'), 'buying_signals', ['created_at'], unique=False)
    op.create_index(op.f('ix_buying_signals_expires_at'), 'buying_signals', ['expires_at'], unique=False)
    op.create_index(op.f('ix_buying_signals_prospect_id'), 'buying_signals', ['prospect_id'], unique=False)
    op.create_index(op.f('ix_buying_signals_signal_type'), 'buying_signals', ['signal_type'], unique=False)
    op.create_index(op.f('ix_buying_signals_tenant_id'), 'buying_signals', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_buying_signals_tenant_id'), table_name='buying_signals')
    op.drop_index(op.f('ix_buying_signals_signal_type'), table_name='buying_signals')
    op.drop_index(op.f('ix_buying_signals_prospect_id'), table_name='buying_signals')
    op.drop_index(op.f('ix_buying_signals_expires_at'), table_name='buying_signals')
    op.drop_index(op.f('ix_buying_signals_created_at'), table_name='buying_signals')
    op.drop_table('buying_signals')
    # ### end Alembic commands ###
